Repository Seol-and-children/byeolbyeol-coffee-frontend, pull requests merged in 2023-12, with the labels that each got.

#6 [Feature][Recipe] 좋아요기능, 레시피 상세보기 페이지 수정
  package-lock.json
  package.json
  src/assets/liked.png
  src/assets/unliked.png
  src/components/recipe/LikeButton.js
  src/pages/AddRecipePage.css
  src/pages/AddRecipePage.js
  src/pages/RecipeDetailViewPage.js
Labels: 🆕Feature, 🛠️Fix

#17 [Feature][Fix][Recipe] 랭킹페이지, 오늘 뭐먹지 구현, 정렬기능 수정
  src/User/pages/Navbar.js
  src/User/styles/Page.css
  src/pages/RankingPage.css
  src/pages/RankingPage.js
  src/pages/RecipeViewPage.css
  src/pages/RecipeViewPage.js
Labels: 🆕Feature, 🛠️Fix

#19 [Feature][Recipe] 커스텀 옵션 기능 구현(개발중)
  src/pages/AddRecipePage.js
  src/pages/RecipeDetailViewPage.js
Labels: 🆕Feature

#25 [Feature][Recipe] 레시피 상세보기 css 구현
  src/admin/franchise/component/FranchiseLogo.jsx
  src/index.js
  src/pages/RecipeDetailViewPage.css
  src/pages/RecipeDetailViewPage.js
Labels: 🆕Feature, 🎨Design

#28 [Feature][Recipe] 카페 별 모아보기 디자인, 프랜차이즈 로고 불러오기 수정 등
  src/admin/franchise/component/FranchiseLogo.jsx
  src/admin/franchise/component/FranchiseLogo.module.css
  src/admin/franchise/css/styles.css
  src/components/recipe/FranchiseFilter.css
  src/components/recipe/FranchiseFilter.js
  src/components/recipe/RecipeCard.css
  src/components/recipe/RecipeCard.js
  src/components/recipe/RecipeGrid.css
  src/pages/RecipeDetailViewPage.css
  src/pages/RecipeDetailViewPage.js
  src/pages/RecipeViewPage.css
  src/pages/RecipeViewPage.js
Labels: 🆕Feature, 🎨Design

#29 [Feature][Recipe][User] 레시피 디자인 수정, UserPage생성
  src/User/Component/UserNickName.js
  src/User/pages/Navbar.js
  src/User/pages/UserPage.js
  src/assets/DoubleArrowDown.svg
  src/assets/DoubleArrowUp.svg
  src/assets/FirstPage.svg
  src/assets/LastPage.svg
  src/assets/Sort.svg
  src/components/common/Pagination.css
  src/components/common/Pagination.js
  src/components/recipe/FranchiseFilter.css
  src/components/recipe/FranchiseFilter.js
  src/pages/RecipeDetailViewPage.css
  src/pages/RecipeDetailViewPage.js
  src/pages/RecipeViewPage.css
  src/pages/RecipeViewPage.js
Labels: 🆕Feature, 🎨Design

#33 상단바 디자인 변경, 폰트 수정
  src/User/Component/UserNickName.module.css
  src/User/pages/Navbar.js
  src/User/pages/Navbar.module.css
  src/admin/franchise/component/FranchiseLogo.module.css
  src/components/recipe/FranchiseFilter.css
  src/components/recipe/RecipeCard.css
  src/components/recipe/RecipeGrid.css
  src/index.css
  src/index.js
  src/main/Main.css
  src/main/components/NewRecipe.js
  src/main/components/RecipeFlex.css
  src/main/components/TodayCoffee.js
  src/pages/RankingPage.css
  src/pages/RecipeDetailViewPage.css
  src/pages/RecipeDetailViewPage.js
  src/pages/RecipeViewPage.css
  src/review/css/CommentWrite.css
  src/review/css/ReviewItem.css
  src/review/css/ReviewList.css
  src/review/css/ReviewWrite.css
Labels: 🎨Design

#39 검색기능 추가
  src/User/pages/Navbar.js
  src/admin/report/component/ReportAddModal.jsx
  src/admin/report/component/ReportList.jsx
  src/admin/report/css/styles.css
  src/index.js
  src/search/component/check_search_result/CheckName.jsx
  src/search/component/check_search_result/CheckRecipe.jsx
  src/search/component/check_search_result/CheckReview.jsx
  src/search/component/check_search_result/nick_name_detail/RecipeByName.jsx
  src/search/component/check_search_result/nick_name_detail/ReviewByName.jsx
  src/search/css/resultStyles.css
  src/search/css/reviewResultStyles.css
Labels: 🆕Feature
